spring.application.name=reactor

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/reactor
spring.r2dbc.username=reactor
spring.r2dbc.password=reactor
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
